using Domain.LinxCommerce.Entities.Parameters;

namespace Application.LinxCommerce.Interfaces
{
    public interface ISKUService
    {
        public Task<bool?> ActivateProduct(LinxCommerceJobParameter jobParameter);
        public Task<bool?> AddProductAssociation(LinxCommerceJobParameter jobParameter);
        public Task<bool?> AddProductAssociations(LinxCommerceJobParameter jobParameter);
        public Task<bool?> AddProductToBundle(LinxCommerceJobParameter jobParameter);
        public Task<bool?> AddSKUsToProducts(LinxCommerceJobParameter jobParameter);
        public Task<bool?> AddSkuToMix(LinxCommerceJobParameter jobParameter);
        public Task<bool?> AddSKUToProduct(LinxCommerceJobParameter jobParameter);
        
        public Task<bool?> ChangeSKUInventories(LinxCommerceJobParameter jobParameter);
        public Task<bool?> ChangeSKUInventory(LinxCommerceJobParameter jobParameter);
        
        public Task<bool?> DeleteAssociationList(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteBrand(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteBundle(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteCatalog(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteCatalogMedia(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteCategory(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteCategoryGroup(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteConditionalProductPrice(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteConditionalProductPrices(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteFlag(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteOffer(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteProduct(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteProductAdditional(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteProductAdditionalList(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteProductAuction(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteProductAuctionBid(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteProductBySku(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteProductDataSource(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteProductPriceChange(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteSKU(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteSKUBySku(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteTag(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DeleteWarehouse(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DesactivateBrand(LinxCommerceJobParameter jobParameter);
        public Task<bool?> DisableProductByIntegrationID(LinxCommerceJobParameter jobParameter);
        public Task<bool?> Dump(LinxCommerceJobParameter jobParameter);
        
        public Task<bool?> EditMixRelation(LinxCommerceJobParameter jobParameter);
        public Task<bool?> EditProductBundleRelation(LinxCommerceJobParameter jobParameter);

        public Task<bool?> GetSKU(LinxCommerceJobParameter jobParameter, int productID);
        public Task<bool?> GetAssociationList(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetBrand(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetBundle(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetBundleBySku(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetCatalog(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetCategory(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetCategoryGroup(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetCategoryProperties(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetCategoryPropertyValues(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetDeletedProduct(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetDeletedSKU(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetFlag(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetMasterCatalog(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetMix(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetMixRelation(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetOffer(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProduct(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductAdditional(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductAdditionalList(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductAuction(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductAuctionBids(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductBundleRelation(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductByIntegrationID(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductCategories(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductCondition(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductDataSource(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductDefinition(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductIDBySkuIntegrationID(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductPrice(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductPriceChange(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductPriceChanges(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductsByIntegrationID(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetProductSEO(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetSKU(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetSKUByIntegrationID(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetSKUsByIntegrationID(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetSupplier(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetTag(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetUnitOfMeasure(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetWarehouse(LinxCommerceJobParameter jobParameter);
        public Task<bool?> GetWarehouseByIntegrationID(LinxCommerceJobParameter jobParameter);

        public Task<bool?> MakeProductAuctionTransition(LinxCommerceJobParameter jobParameter);
        public Task<bool?> MergeConditionalProductPrice(LinxCommerceJobParameter jobParameter);
        public Task<bool?> MergeConditionalProductPrices(LinxCommerceJobParameter jobParameter);
        public Task<bool?> MoveCategory(LinxCommerceJobParameter jobParameter);

        public Task<bool?> RemoveCatalogItem(LinxCommerceJobParameter jobParameter);
        public Task<bool?> RemoveProductAssociation(LinxCommerceJobParameter jobParameter);
        public Task<bool?> RemoveProductAssociations(LinxCommerceJobParameter jobParameter);
        public Task<bool?> RemoveProductFromBundle(LinxCommerceJobParameter jobParameter);
        public Task<bool?> RemoveSKUFromMix(LinxCommerceJobParameter jobParameter);
        public Task<bool?> RemoveSKUFromProduct(LinxCommerceJobParameter jobParameter);
        public Task<bool?> RunProductWorkflow(LinxCommerceJobParameter jobParameter);

        public Task<bool?> SaveAssociationList(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveAssociationLists(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveBrand(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveBrands(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveBundle(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveBundles(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveCatalog(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveCatalogMedia(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveCatalogMixMedia(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveCatalogs(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveCategories(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveCategory(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveCategoryGroup (LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveCategoryGroups (LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveFlag (LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveFlags(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveMix(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveMixes(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveOffer(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveOffers(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProduct(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductAdditional(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductAdditionalList(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductAuction(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductAuctionBid(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductDataSource(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductDefinition(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductPrice(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductPriceBulk(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductPriceChange(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductPriceChanges(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductPrices(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductReview(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProductReviews(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveProducts(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveSKU(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveSKUs(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveSKUToProduct (LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveSupplier(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveSuppliers(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveTag(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveTags(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveUnitOfMeasure(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveUnitOfMeasures(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveWarehouse (LinxCommerceJobParameter jobParameter);
        public Task<bool?> SaveWarehouses(LinxCommerceJobParameter jobParameter);

        public Task<bool?> SearchAssociationList(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchBrands(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchBundle(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchCatalog(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchCategory(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchCategoryGroups(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchFlag(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchMix(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchOffers(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductByDateInterval(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductByQueue(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductAdditionalLists(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductAdditionals(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductAuctions(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductConditions(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductDataSource(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductDefinitions(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductPrices(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductReviews(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchProductShortDefinitions(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchSKUByDateInterval(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchSKUByQueue(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchSupplier(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchTags(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchUnitOfMeasure(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SearchWarehouse(LinxCommerceJobParameter jobParameter);

        public Task<bool?> SetProductAuctionWinner(LinxCommerceJobParameter jobParameter);
        public Task<bool?> SetProductVisibility(LinxCommerceJobParameter jobParameter);
        public Task<bool?> UpdateOfferStatus(LinxCommerceJobParameter jobParameter);
        public Task<bool?> UpdateProduct(LinxCommerceJobParameter jobParameter);
    }
}
