using Application.IntegrationsCore.Validations.Extensions;
using Domain.LinxMicrovix.Outbound.WebService.Dtos.LinxMicrovix;
using FluentValidation;

namespace Application.LinxMicrovix.Outbound.WebService.CustomValidations.LinxMicrovix
{
    public class LinxConfiguracoesTributariasDetalhesValidator : AbstractValidator<LinxConfiguracoesTributariasDetalhes>
    {
        public LinxConfiguracoesTributariasDetalhesValidator()
        {
            RuleFor(x => x.portal).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.portal));
            RuleFor(x => x.cnpj_emp).MaximumLength(14).WithMessage("O campo 'cnpj_emp' deve ter no máximo 14 caracteres.").When(x => !string.IsNullOrEmpty(x.cnpj_emp));
            RuleFor(x => x.id_config_tributaria).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_config_tributaria));
            RuleFor(x => x.desc_classe_fiscal).MaximumLength(150).WithMessage("O campo 'desc_classe_fiscal' deve ter no máximo 150 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_classe_fiscal));
            RuleFor(x => x.cod_natureza_operacao).MaximumLength(10).WithMessage("O campo 'cod_natureza_operacao' deve ter no máximo 10 caracteres.").When(x => !string.IsNullOrEmpty(x.cod_natureza_operacao));
            RuleFor(x => x.desc_natureza_operacao).MaximumLength(60).WithMessage("O campo 'desc_natureza_operacao' deve ter no máximo 60 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_natureza_operacao));
            RuleFor(x => x.cfop_fiscal).MaximumLength(5).WithMessage("O campo 'cfop_fiscal' deve ter no máximo 5 caracteres.").When(x => !string.IsNullOrEmpty(x.cfop_fiscal));
            RuleFor(x => x.desc_cfop_fiscal).MaximumLength(300).WithMessage("O campo 'desc_cfop_fiscal' deve ter no máximo 300 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_cfop_fiscal));
            RuleFor(x => x.aliq_icms).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_icms));
            RuleFor(x => x.valor_tributado_icms).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.valor_tributado_icms));
            RuleFor(x => x.aliq_pis).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_pis));
            RuleFor(x => x.aliq_cofins).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_cofins));
            RuleFor(x => x.perc_reducao_icms).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.perc_reducao_icms));
            RuleFor(x => x.perc_reducao_icms_st).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.perc_reducao_icms_st));
            RuleFor(x => x.margem_st).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.margem_st));
            RuleFor(x => x.aliquota_st).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_st));
            RuleFor(x => x.margem_st_simulador).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.margem_st_simulador));
            RuleFor(x => x.aliquota_st_simulador).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_st_simulador));
            RuleFor(x => x.desconto_icms).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.desconto_icms));
            RuleFor(x => x.cst_icms_fiscal).MaximumLength(4).WithMessage("O campo 'cst_icms_fiscal' deve ter no máximo 4 caracteres.").When(x => !string.IsNullOrEmpty(x.cst_icms_fiscal));
            RuleFor(x => x.desc_cst_icms_fiscal).MaximumLength(150).WithMessage("O campo 'desc_cst_icms_fiscal' deve ter no máximo 150 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_cst_icms_fiscal));
            RuleFor(x => x.cst_ipi_fiscal).MaximumLength(4).WithMessage("O campo 'cst_ipi_fiscal' deve ter no máximo 4 caracteres.").When(x => !string.IsNullOrEmpty(x.cst_ipi_fiscal));
            RuleFor(x => x.desc_cst_ipi_fiscal).MaximumLength(150).WithMessage("O campo 'desc_cst_ipi_fiscal' deve ter no máximo 150 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_cst_ipi_fiscal));
            RuleFor(x => x.cst_pis_fiscal).MaximumLength(4).WithMessage("O campo 'cst_pis_fiscal' deve ter no máximo 4 caracteres.").When(x => !string.IsNullOrEmpty(x.cst_pis_fiscal));
            RuleFor(x => x.desc_cst_pis_fiscal).MaximumLength(150).WithMessage("O campo 'desc_cst_pis_fiscal' deve ter no máximo 150 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_cst_pis_fiscal));
            RuleFor(x => x.cst_cofins_fiscal).MaximumLength(4).WithMessage("O campo 'cst_cofins_fiscal' deve ter no máximo 4 caracteres.").When(x => !string.IsNullOrEmpty(x.cst_cofins_fiscal));
            RuleFor(x => x.desc_cst_cofins_fiscal).MaximumLength(150).WithMessage("O campo 'desc_cst_cofins_fiscal' deve ter no máximo 150 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_cst_cofins_fiscal));
            RuleFor(x => x.desc_obs_padrao).MaximumLength(250).WithMessage("O campo 'desc_obs_padrao' deve ter no máximo 250 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_obs_padrao));
            RuleFor(x => x.icms_credito).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.icms_credito));
            RuleFor(x => x.ipi_credito).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.ipi_credito));
            RuleFor(x => x.cod_enquadramento_ipi).MaximumLength(3).WithMessage("O campo 'cod_enquadramento_ipi' deve ter no máximo 3 caracteres.").When(x => !string.IsNullOrEmpty(x.cod_enquadramento_ipi));
            RuleFor(x => x.desc_enquadramento_ipi).MaximumLength(600).WithMessage("O campo 'desc_enquadramento_ipi' deve ter no máximo 600 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_enquadramento_ipi));
            RuleFor(x => x.perc_aliquota_interna_uf_destinatario).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.perc_aliquota_interna_uf_destinatario));
            RuleFor(x => x.perc_aliquota_interestadual_uf_envolvidas).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.perc_aliquota_interestadual_uf_envolvidas));
            RuleFor(x => x.csosn_fiscal).MaximumLength(5).WithMessage("O campo 'csosn_fiscal' deve ter no máximo 5 caracteres.").When(x => !string.IsNullOrEmpty(x.csosn_fiscal));
            RuleFor(x => x.desc_csosn_fiscal).MaximumLength(200).WithMessage("O campo 'desc_csosn_fiscal' deve ter no máximo 200 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_csosn_fiscal));
            RuleFor(x => x.forma_tributacao_pis).MaximumLength(10).WithMessage("O campo 'forma_tributacao_pis' deve ter no máximo 10 caracteres.").When(x => !string.IsNullOrEmpty(x.forma_tributacao_pis));
            RuleFor(x => x.forma_tributacao_cofins).MaximumLength(10).WithMessage("O campo 'forma_tributacao_cofins' deve ter no máximo 10 caracteres.").When(x => !string.IsNullOrEmpty(x.forma_tributacao_cofins));
            RuleFor(x => x.id_ramo_atividade).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_ramo_atividade));
            RuleFor(x => x.empresa).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.empresa));
            RuleFor(x => x.usa_base_icms_para_calculo_st).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.usa_base_icms_para_calculo_st));
            RuleFor(x => x.id_classe_fiscal).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_classe_fiscal));
            RuleFor(x => x.id_cfop_fiscal).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_cfop_fiscal));
            RuleFor(x => x.id_cst_icms_fiscal).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_cst_icms_fiscal));
            RuleFor(x => x.id_cst_ipi_fiscal).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_cst_ipi_fiscal));
            RuleFor(x => x.id_cst_pis_fiscal).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_cst_pis_fiscal));
            RuleFor(x => x.id_cst_cofins_fiscal).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_cst_cofins_fiscal));
            RuleFor(x => x.id_obs).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_obs));
            RuleFor(x => x.tributado).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.tributado));
            RuleFor(x => x.retido).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.retido));
            RuleFor(x => x.icms_base_naotributado).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.icms_base_naotributado));
            RuleFor(x => x.ipi_base_naotributado).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.ipi_base_naotributado));
            RuleFor(x => x.id_csosn_fiscal).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_csosn_fiscal));
            RuleFor(x => x.somar_icms_st).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.somar_icms_st));
            RuleFor(x => x.id_sped_tipo_base_credito).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_sped_tipo_base_credito));
            RuleFor(x => x.aliq_pis_servico).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_pis_servico));
            RuleFor(x => x.aliq_cofins_servico).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_cofins_servico));
            RuleFor(x => x.id_cst_pis_fiscal_servico).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_cst_pis_fiscal_servico));
            RuleFor(x => x.id_cst_cofins_fiscal_servico).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_cst_cofins_fiscal_servico));
            RuleFor(x => x.csrf).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.csrf));
            RuleFor(x => x.codigo_retencao_csrf).MaximumLength(4).WithMessage("O campo 'codigo_retencao_csrf' deve ter no máximo 4 caracteres.").When(x => !string.IsNullOrEmpty(x.codigo_retencao_csrf));
            RuleFor(x => x.aliq_pis_csrf).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_pis_csrf));
            RuleFor(x => x.aliq_cofins_csrf).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_cofins_csrf));
            RuleFor(x => x.aliq_csll_csrf).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_csll_csrf));
            RuleFor(x => x.id_sped_tipo_base_credito_servico).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_sped_tipo_base_credito_servico));
            RuleFor(x => x.receita).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.receita));
            RuleFor(x => x.fci_informa_parcela_importada).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.fci_informa_parcela_importada));
            RuleFor(x => x.fci_informa_numero).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.fci_informa_numero));
            RuleFor(x => x.fci_informa_conteudo_importacao).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.fci_informa_conteudo_importacao));
            RuleFor(x => x.fci_informa_valor_importacao).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.fci_informa_valor_importacao));
            RuleFor(x => x.iss_tipo_tributacao).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.iss_tipo_tributacao));
            RuleFor(x => x.icms_st_antecipado_margem).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_st_antecipado_margem));
            RuleFor(x => x.icms_st_antecipado_aliquota).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_st_antecipado_aliquota));
            RuleFor(x => x.icms_st_antecipado_percentual_reducao).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_st_antecipado_percentual_reducao));
            RuleFor(x => x.icms_st_antecipado_valor_integra_custo_medio).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.icms_st_antecipado_valor_integra_custo_medio));
            RuleFor(x => x.id_enquadramento_ipi).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_enquadramento_ipi));
            RuleFor(x => x.usa_regime_estimativa_simplifica).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.usa_regime_estimativa_simplifica));
            RuleFor(x => x.aliq_carga_tributaria_media).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_carga_tributaria_media));
            RuleFor(x => x.fcp_integra_custo_medio).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.fcp_integra_custo_medio));
            RuleFor(x => x.aliq_fcp).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_fcp));
            RuleFor(x => x.fcp_credito).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.fcp_credito));
            RuleFor(x => x.fcp_reducao_icms).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.fcp_reducao_icms));
            RuleFor(x => x.aliq_icms_efetivo).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_icms_efetivo));
            RuleFor(x => x.perc_reducao_icms_efetivo).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.perc_reducao_icms_efetivo));
            RuleFor(x => x.icms_fcp_st_antecipado_aliquota).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_fcp_st_antecipado_aliquota));
            RuleFor(x => x.difal_base_dupla).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.difal_base_dupla));
            RuleFor(x => x.aliq_desoneracao_icms).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_desoneracao_icms));
            RuleFor(x => x.aliq_desoneracao_fcp).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_desoneracao_fcp));
            RuleFor(x => x.cod_beneficio_fiscal).MaximumLength(10).WithMessage("O campo 'cod_beneficio_fiscal' deve ter no máximo 10 caracteres.").When(x => !string.IsNullOrEmpty(x.cod_beneficio_fiscal));
            RuleFor(x => x.id_motivo_desoneracao_icms).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_motivo_desoneracao_icms));
            RuleFor(x => x.deduzir_icms_custo).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.deduzir_icms_custo));
            RuleFor(x => x.deduzir_icms_desonerado).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.deduzir_icms_desonerado));
            RuleFor(x => x.somar_ipi_base_difal_fcp).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.somar_ipi_base_difal_fcp));
            RuleFor(x => x.tipo_base_dupla).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.tipo_base_dupla));
            RuleFor(x => x.utiliza_lucro_base_icms).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.utiliza_lucro_base_icms));
            RuleFor(x => x.utiliza_lucro_base_pis).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.utiliza_lucro_base_pis));
            RuleFor(x => x.utiliza_lucro_base_cofins).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.utiliza_lucro_base_cofins));
            RuleFor(x => x.codigo_ws).MaximumLength(100).WithMessage("O campo 'codigo_ws' deve ter no máximo 100 caracteres.").When(x => !string.IsNullOrEmpty(x.codigo_ws));
            RuleFor(x => x.timestamp).MustBeValidInt64().When(x => !string.IsNullOrEmpty(x.timestamp));
            RuleFor(x => x.aliquota_diferimento_icms).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_diferimento_icms));
            RuleFor(x => x.aliquota_diferimento_fcp).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_diferimento_fcp));
        }
    }
}
