namespace Domain.LinxMicrovix.Outbound.WebService.Entities.Base.LinxMicrovix
{
    public abstract class LinxConfiguracoesTributariasDetalhes
    {
        public string? portal { get; set; }
        public string? cnpj_emp { get; set; }
        public string? id_config_tributaria { get; set; }
        public string? desc_classe_fiscal { get; set; }
        public string? cod_natureza_operacao { get; set; }
        public string? desc_natureza_operacao { get; set; }
        public string? cfop_fiscal { get; set; }
        public string? desc_cfop_fiscal { get; set; }
        public string? aliq_icms { get; set; }
        public string? valor_tributado_icms { get; set; }
        public string? aliq_pis { get; set; }
        public string? aliq_cofins { get; set; }
        public string? perc_reducao_icms { get; set; }
        public string? perc_reducao_icms_st { get; set; }
        public string? margem_st { get; set; }
        public string? aliquota_st { get; set; }
        public string? margem_st_simulador { get; set; }
        public string? aliquota_st_simulador { get; set; }
        public string? desconto_icms { get; set; }
        public string? cst_icms_fiscal { get; set; }
        public string? desc_cst_icms_fiscal { get; set; }
        public string? cst_ipi_fiscal { get; set; }
        public string? desc_cst_ipi_fiscal { get; set; }
        public string? cst_pis_fiscal { get; set; }
        public string? desc_cst_pis_fiscal { get; set; }
        public string? cst_cofins_fiscal { get; set; }
        public string? desc_cst_cofins_fiscal { get; set; }
        public string? desc_obs_padrao { get; set; }
        public string? icms_credito { get; set; }
        public string? ipi_credito { get; set; }
        public string? cod_enquadramento_ipi { get; set; }
        public string? desc_enquadramento_ipi { get; set; }
        public string? perc_aliquota_interna_uf_destinatario { get; set; }
        public string? perc_aliquota_interestadual_uf_envolvidas { get; set; }
        public string? csosn_fiscal { get; set; }
        public string? desc_csosn_fiscal { get; set; }
        public string? forma_tributacao_pis { get; set; }
        public string? forma_tributacao_cofins { get; set; }
        public string? id_ramo_atividade { get; set; }
        public string? empresa { get; set; }
        public string? usa_base_icms_para_calculo_st { get; set; }
        public string? id_classe_fiscal { get; set; }
        public string? id_cfop_fiscal { get; set; }
        public string? id_cst_icms_fiscal { get; set; }
        public string? id_cst_ipi_fiscal { get; set; }
        public string? id_cst_pis_fiscal { get; set; }
        public string? id_cst_cofins_fiscal { get; set; }
        public string? id_obs { get; set; }
        public string? tributado { get; set; }
        public string? retido { get; set; }
        public string? icms_base_naotributado { get; set; }
        public string? ipi_base_naotributado { get; set; }
        public string? id_csosn_fiscal { get; set; }
        public string? somar_icms_st { get; set; }
        public string? id_sped_tipo_base_credito { get; set; }
        public string? aliq_pis_servico { get; set; }
        public string? aliq_cofins_servico { get; set; }
        public string? id_cst_pis_fiscal_servico { get; set; }
        public string? id_cst_cofins_fiscal_servico { get; set; }
        public string? csrf { get; set; }
        public string? codigo_retencao_csrf { get; set; }
        public string? aliq_pis_csrf { get; set; }
        public string? aliq_cofins_csrf { get; set; }
        public string? aliq_csll_csrf { get; set; }
        public string? id_sped_tipo_base_credito_servico { get; set; }
        public string? receita { get; set; }
        public string? fci_informa_parcela_importada { get; set; }
        public string? fci_informa_numero { get; set; }
        public string? fci_informa_conteudo_importacao { get; set; }
        public string? fci_informa_valor_importacao { get; set; }
        public string? iss_tipo_tributacao { get; set; }
        public string? icms_st_antecipado_margem { get; set; }
        public string? icms_st_antecipado_aliquota { get; set; }
        public string? icms_st_antecipado_percentual_reducao { get; set; }
        public string? icms_st_antecipado_valor_integra_custo_medio { get; set; }
        public string? id_enquadramento_ipi { get; set; }
        public string? usa_regime_estimativa_simplifica { get; set; }
        public string? aliq_carga_tributaria_media { get; set; }
        public string? fcp_integra_custo_medio { get; set; }
        public string? aliq_fcp { get; set; }
        public string? fcp_credito { get; set; }
        public string? fcp_reducao_icms { get; set; }
        public string? aliq_icms_efetivo { get; set; }
        public string? perc_reducao_icms_efetivo { get; set; }
        public string? icms_fcp_st_antecipado_aliquota { get; set; }
        public string? difal_base_dupla { get; set; }
        public string? aliq_desoneracao_icms { get; set; }
        public string? aliq_desoneracao_fcp { get; set; }
        public string? cod_beneficio_fiscal { get; set; }
        public string? id_motivo_desoneracao_icms { get; set; }
        public string? deduzir_icms_custo { get; set; }
        public string? deduzir_icms_desonerado { get; set; }
        public string? somar_ipi_base_difal_fcp { get; set; }
        public string? tipo_base_dupla { get; set; }
        public string? utiliza_lucro_base_icms { get; set; }
        public string? utiliza_lucro_base_pis { get; set; }
        public string? utiliza_lucro_base_cofins { get; set; }
        public string? codigo_ws { get; set; }
        public string? timestamp { get; set; }
        public string? aliquota_diferimento_icms { get; set; }
        public string? aliquota_diferimento_fcp { get; set; }
    }
}
