namespace Domain.LinxMicrovix.Outbound.WebService.Entities.Base.LinxMicrovix
{
    public abstract class LinxOticoReceitas
    {
        public string? id_otico_receitas { get; set; }
        public string? cod_cliente { get; set; }
        public string? codigoproduto { get; set; }
        public string? lng_esferico_od { get; set; }
        public string? lng_cilindrico_od { get; set; }
        public string? lng_eixo_od { get; set; }
        public string? lng_dpdpn_od { get; set; }
        public string? lng_altura_od { get; set; }
        public string? prt_esferico_od { get; set; }
        public string? prt_cilindrico_od { get; set; }
        public string? prt_eixo_od { get; set; }
        public string? prt_dpdpn_od { get; set; }
        public string? lng_esferico_oe { get; set; }
        public string? lng_cilindrico_oe { get; set; }
        public string? lng_eixo_oe { get; set; }
        public string? lng_dpdpn_oe { get; set; }
        public string? lng_altura_oe { get; set; }
        public string? prt_esferico_oe { get; set; }
        public string? prt_cilindrico_oe { get; set; }
        public string? prt_eixo_oe { get; set; }
        public string? prt_dpdpn_oe { get; set; }
        public string? lng_adicao_od { get; set; }
        public string? lng_adicao_oe { get; set; }
        public string? otico_lado_lente { get; set; }
        public string? diametro_od { get; set; }
        public string? diametro_oe { get; set; }
        public string? ponte { get; set; }
        public string? altura { get; set; }
        public string? aro { get; set; }
        public string? diag_maior { get; set; }
        public string? tipo_armacao { get; set; }
        public string? observacao { get; set; }
        public string? paciente { get; set; }
        public string? cmpl_add_od { get; set; }
        public string? cmpl_add_oe { get; set; }
        public string? base_od { get; set; }
        public string? base_oe { get; set; }
        public string? dist_haste { get; set; }
        public string? dist_front { get; set; }
        public string? curvatura { get; set; }
        public string? lng_pris1_od { get; set; }
        public string? id_lng_pris1_od_desc { get; set; }
        public string? lng_pris1_oe { get; set; }
        public string? id_lng_pris1_oe_desc { get; set; }
        public string? prt_pris1_od { get; set; }
        public string? id_prt_pris1_od_desc { get; set; }
        public string? prt_pris1_oe { get; set; }
        public string? id_prt_pris1_oe_desc { get; set; }
        public string? lng_pris2_od { get; set; }
        public string? id_lng_pris2_od_desc { get; set; }
        public string? lng_pris2_oe { get; set; }
        public string? id_lng_pris2_oe_desc { get; set; }
        public string? prt_pris2_od { get; set; }
        public string? id_prt_pris2_od_desc { get; set; }
        public string? prt_pris2_oe { get; set; }
        public string? id_prt_pris2_oe_desc { get; set; }
        public string? dist_vertice { get; set; }
        public string? inc_planto { get; set; }
        public string? ativ_princ { get; set; }
        public string? otico_area_privilegiada { get; set; }
        public string? dist_visao { get; set; }
        public string? personalizada { get; set; }
        public string? pris_od { get; set; }
        public string? pris_oe { get; set; }
        public string? eixo_od { get; set; }
        public string? eixo_oe { get; set; }
        public string? borda_od { get; set; }
        public string? borda_oe { get; set; }
        public string? centro_od { get; set; }
        public string? centro_oe { get; set; }
        public string? furo_od { get; set; }
        public string? furo_oe { get; set; }
        public string? format_corte { get; set; }
        public string? dist_leitura { get; set; }
        public string? tipo_lente { get; set; }
        public string? endereco_paciente { get; set; }
        public string? medico_especialista { get; set; }
        public string? endereco_medico_especialista { get; set; }
        public string? refracionista_optico { get; set; }
        public string? data_receita { get; set; }
        public string? id_produtos_opticos_tipo_aro { get; set; }
        public string? dp_montagem { get; set; }
        public string? id_produtos_opticos_formato_aro { get; set; }
        public string? codigo_gerencial { get; set; }
        public string? migracao_dados { get; set; }
        public string? migracao_observacao { get; set; }
        public string? portal { get; set; }
        public string? timestamp { get; set; }
    }
}
