using Application.Core.Validations.Extensions;
using Domain.LinxMicrovix.Outbound.WebService.Dtos.LinxMicrovix;
using FluentValidation;

namespace Application.LinxMicrovix.Outbound.WebService.Validations.LinxMicrovix
{
    public class LinxMovimentoValidator : AbstractValidator<LinxMovimento>
    {
        public LinxMovimentoValidator()
        {
            RuleFor(x => x.portal).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.portal));
            RuleFor(x => x.cnpj_emp).MaximumLength(14).WithMessage("O campo 'cnpj_emp' deve ter no máximo 14 caracteres.").When(x => !string.IsNullOrEmpty(x.cnpj_emp));
            RuleFor(x => x.transacao).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.transacao));
            RuleFor(x => x.usuario).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.usuario));
            RuleFor(x => x.documento).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.documento));
            RuleFor(x => x.chave_nf).MaximumLength(44).WithMessage("O campo 'chave_nf' deve ter no máximo 44 caracteres.").When(x => !string.IsNullOrEmpty(x.chave_nf));
            RuleFor(x => x.ecf).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.ecf));
            RuleFor(x => x.numero_serie_ecf).MaximumLength(30).WithMessage("O campo 'numero_serie_ecf' deve ter no máximo 30 caracteres.").When(x => !string.IsNullOrEmpty(x.numero_serie_ecf));
            RuleFor(x => x.modelo_nf).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.modelo_nf));
            RuleFor(x => x.data_documento).MustBeValidDateTime().When(x => !string.IsNullOrEmpty(x.data_documento));
            RuleFor(x => x.data_lancamento).MustBeValidDateTime().When(x => !string.IsNullOrEmpty(x.data_lancamento));
            RuleFor(x => x.codigo_cliente).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.codigo_cliente));
            RuleFor(x => x.serie).MaximumLength(10).WithMessage("O campo 'serie' deve ter no máximo 10 caracteres.").When(x => !string.IsNullOrEmpty(x.serie));
            RuleFor(x => x.desc_cfop).MaximumLength(300).WithMessage("O campo 'desc_cfop' deve ter no máximo 300 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_cfop));
            RuleFor(x => x.id_cfop).MaximumLength(5).WithMessage("O campo 'id_cfop' deve ter no máximo 5 caracteres.").When(x => !string.IsNullOrEmpty(x.id_cfop));
            RuleFor(x => x.cod_vendedor).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.cod_vendedor));
            RuleFor(x => x.quantidade).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.quantidade));
            RuleFor(x => x.preco_custo).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.preco_custo));
            RuleFor(x => x.valor_liquido).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.valor_liquido));
            RuleFor(x => x.desconto).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.desconto));
            RuleFor(x => x.cst_icms).MaximumLength(4).WithMessage("O campo 'cst_icms' deve ter no máximo 4 caracteres.").When(x => !string.IsNullOrEmpty(x.cst_icms));
            RuleFor(x => x.cst_pis).MaximumLength(4).WithMessage("O campo 'cst_pis' deve ter no máximo 4 caracteres.").When(x => !string.IsNullOrEmpty(x.cst_pis));
            RuleFor(x => x.cst_cofins).MaximumLength(4).WithMessage("O campo 'cst_cofins' deve ter no máximo 4 caracteres.").When(x => !string.IsNullOrEmpty(x.cst_cofins));
            RuleFor(x => x.cst_ipi).MaximumLength(4).WithMessage("O campo 'cst_ipi' deve ter no máximo 4 caracteres.").When(x => !string.IsNullOrEmpty(x.cst_ipi));
            RuleFor(x => x.valor_icms).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.valor_icms));
            RuleFor(x => x.aliquota_icms).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_icms));
            RuleFor(x => x.base_icms).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.base_icms));
            RuleFor(x => x.valor_pis).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.valor_pis));
            RuleFor(x => x.aliquota_pis).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_pis));
            RuleFor(x => x.base_pis).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.base_pis));
            RuleFor(x => x.valor_cofins).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.valor_cofins));
            RuleFor(x => x.aliquota_cofins).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_cofins));
            RuleFor(x => x.base_cofins).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.base_cofins));
            RuleFor(x => x.valor_icms_st).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.valor_icms_st));
            RuleFor(x => x.aliquota_icms_st).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_icms_st));
            RuleFor(x => x.base_icms_st).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.base_icms_st));
            RuleFor(x => x.valor_ipi).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.valor_ipi));
            RuleFor(x => x.aliquota_ipi).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_ipi));
            RuleFor(x => x.base_ipi).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.base_ipi));
            RuleFor(x => x.valor_total).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.valor_total));
            RuleFor(x => x.forma_dinheiro).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.forma_dinheiro));
            RuleFor(x => x.total_dinheiro).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.total_dinheiro));
            RuleFor(x => x.forma_cheque).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.forma_cheque));
            RuleFor(x => x.total_cheque).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.total_cheque));
            RuleFor(x => x.forma_cartao).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.forma_cartao));
            RuleFor(x => x.total_cartao).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.total_cartao));
            RuleFor(x => x.forma_crediario).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.forma_crediario));
            RuleFor(x => x.total_crediario).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.total_crediario));
            RuleFor(x => x.forma_convenio).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.forma_convenio));
            RuleFor(x => x.total_convenio).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.total_convenio));
            RuleFor(x => x.frete).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.frete));
            RuleFor(x => x.operacao).MaximumLength(2).WithMessage("O campo 'operacao' deve ter no máximo 2 caracteres.").When(x => !string.IsNullOrEmpty(x.operacao));
            RuleFor(x => x.tipo_transacao).MaximumLength(1).WithMessage("O campo 'tipo_transacao' deve ter no máximo 1 caractere.").When(x => !string.IsNullOrEmpty(x.tipo_transacao));
            RuleFor(x => x.cod_produto).MustBeValidInt64().When(x => !string.IsNullOrEmpty(x.cod_produto));
            RuleFor(x => x.cod_barra).MaximumLength(20).WithMessage("O campo 'cod_barra' deve ter no máximo 20 caracteres.").When(x => !string.IsNullOrEmpty(x.cod_barra));
            RuleFor(x => x.cancelado).MaximumLength(1).WithMessage("O campo 'cancelado' deve ter no máximo 1 caractere.").When(x => !string.IsNullOrEmpty(x.cancelado));
            RuleFor(x => x.excluido).MaximumLength(1).WithMessage("O campo 'excluido' deve ter no máximo 1 caractere.").When(x => !string.IsNullOrEmpty(x.excluido));
            RuleFor(x => x.soma_relatorio).MaximumLength(1).WithMessage("O campo 'soma_relatorio' deve ter no máximo 1 caractere.").When(x => !string.IsNullOrEmpty(x.soma_relatorio));
            RuleFor(x => x.identificador).Must(value => Guid.TryParse(value, out _)).WithMessage("O campo 'identificador' deve ser um GUID válido.").When(x => !string.IsNullOrEmpty(x.identificador));
            RuleFor(x => x.deposito).MaximumLength(100).WithMessage("O campo 'deposito' deve ter no máximo 100 caracteres.").When(x => !string.IsNullOrEmpty(x.deposito));
            RuleFor(x => x.preco_unitario).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.preco_unitario));
            RuleFor(x => x.hora_lancamento).MaximumLength(5).WithMessage("O campo 'hora_lancamento' deve ter no máximo 5 caracteres.").When(x => !string.IsNullOrEmpty(x.hora_lancamento));
            RuleFor(x => x.natureza_operacao).MaximumLength(60).WithMessage("O campo 'natureza_operacao' deve ter no máximo 60 caracteres.").When(x => !string.IsNullOrEmpty(x.natureza_operacao));
            RuleFor(x => x.tabela_preco).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.tabela_preco));
            RuleFor(x => x.nome_tabela_preco).MaximumLength(50).WithMessage("O campo 'nome_tabela_preco' deve ter no máximo 50 caracteres.").When(x => !string.IsNullOrEmpty(x.nome_tabela_preco));
            RuleFor(x => x.cod_sefaz_situacao).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.cod_sefaz_situacao));
            RuleFor(x => x.desc_sefaz_situacao).MaximumLength(30).WithMessage("O campo 'desc_sefaz_situacao' deve ter no máximo 30 caracteres.").When(x => !string.IsNullOrEmpty(x.desc_sefaz_situacao));
            RuleFor(x => x.protocolo_aut_nfe).MaximumLength(15).WithMessage("O campo 'protocolo_aut_nfe' deve ter no máximo 15 caracteres.").When(x => !string.IsNullOrEmpty(x.protocolo_aut_nfe));
            RuleFor(x => x.dt_update).MustBeValidDateTime().When(x => !string.IsNullOrEmpty(x.dt_update));
            RuleFor(x => x.forma_cheque_prazo).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.forma_cheque_prazo));
            RuleFor(x => x.total_cheque_prazo).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.total_cheque_prazo));
            RuleFor(x => x.cod_natureza_operacao).MaximumLength(10).WithMessage("O campo 'cod_natureza_operacao' deve ter no máximo 10 caracteres.").When(x => !string.IsNullOrEmpty(x.cod_natureza_operacao));
            RuleFor(x => x.preco_tabela_epoca).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.preco_tabela_epoca));
            RuleFor(x => x.desconto_total_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.desconto_total_item));
            RuleFor(x => x.conferido).MaximumLength(1).WithMessage("O campo 'conferido' deve ter no máximo 1 caractere.").When(x => !string.IsNullOrEmpty(x.conferido));
            RuleFor(x => x.transacao_pedido_venda).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.transacao_pedido_venda));
            RuleFor(x => x.codigo_modelo_nf).MaximumLength(5).WithMessage("O campo 'codigo_modelo_nf' deve ter no máximo 5 caracteres.").When(x => !string.IsNullOrEmpty(x.codigo_modelo_nf));
            RuleFor(x => x.acrescimo).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.acrescimo));
            RuleFor(x => x.mob_checkout).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.mob_checkout));
            RuleFor(x => x.aliquota_iss).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliquota_iss));
            RuleFor(x => x.base_iss).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.base_iss));
            RuleFor(x => x.ordem).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.ordem));
            RuleFor(x => x.codigo_rotina_origem).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.codigo_rotina_origem));
            RuleFor(x => x.timestamp).MustBeValidInt64().When(x => !string.IsNullOrEmpty(x.timestamp));
            RuleFor(x => x.troco).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.troco));
            RuleFor(x => x.transportador).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.transportador));
            RuleFor(x => x.icms_aliquota_desonerado).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_aliquota_desonerado));
            RuleFor(x => x.icms_valor_desonerado_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_valor_desonerado_item));
            RuleFor(x => x.empresa).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.empresa));
            RuleFor(x => x.desconto_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.desconto_item));
            RuleFor(x => x.aliq_iss).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.aliq_iss));
            RuleFor(x => x.iss_base_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.iss_base_item));
            RuleFor(x => x.despesas).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.despesas));
            RuleFor(x => x.seguro_total_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.seguro_total_item));
            RuleFor(x => x.acrescimo_total_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.acrescimo_total_item));
            RuleFor(x => x.despesas_total_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.despesas_total_item));
            RuleFor(x => x.forma_pix).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.forma_pix));
            RuleFor(x => x.total_pix).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.total_pix));
            RuleFor(x => x.forma_deposito_bancario).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.forma_deposito_bancario));
            RuleFor(x => x.total_deposito_bancario).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.total_deposito_bancario));
            RuleFor(x => x.id_venda_produto_b2c).MustBeValidInt32().When(x => !string.IsNullOrEmpty(x.id_venda_produto_b2c));
            RuleFor(x => x.item_promocional).MustBeValidBoolean().When(x => !string.IsNullOrEmpty(x.item_promocional));
            RuleFor(x => x.acrescimo_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.acrescimo_item));
            RuleFor(x => x.icms_st_antecipado_aliquota).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_st_antecipado_aliquota));
            RuleFor(x => x.icms_st_antecipado_margem).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_st_antecipado_margem));
            RuleFor(x => x.icms_st_antecipado_percentual_reducao).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_st_antecipado_percentual_reducao));
            RuleFor(x => x.icms_st_antecipado_valor_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_st_antecipado_valor_item));
            RuleFor(x => x.icms_base_desonerado_item).MustBeValidDecimal().When(x => !string.IsNullOrEmpty(x.icms_base_desonerado_item));
            RuleFor(x => x.codigo_status_nfe).MaximumLength(5).WithMessage("O campo 'codigo_status_nfe' deve ter no máximo 5 caracteres.").When(x => !string.IsNullOrEmpty(x.codigo_status_nfe));
        }
    }
}
