namespace Domain.LinxMicrovix.Outbound.WebService.Entities.Base.LinxMicrovix
{
    public abstract class LinxDadosOpticosDav
    {
        public string? id_vendas_pos_produtos { get; set; }
        public string? cod_produto { get; set; }
        public string? dav { get; set; }
        public string? tipo_lente { get; set; }
        public string? od_oe { get; set; }
        public string? lng_esferico_od { get; set; }
        public string? lng_cilindrico_od { get; set; }
        public string? lng_eixo_od { get; set; }
        public string? lng_esferico_oe { get; set; }
        public string? lng_cilindrico_oe { get; set; }
        public string? lng_eixo_oe { get; set; }
        public string? prt_esferico_od { get; set; }
        public string? prt_cilindrico_od { get; set; }
        public string? prt_eixo_od { get; set; }
        public string? prt_esferico_oe { get; set; }
        public string? prt_cilindrico_oe { get; set; }
        public string? prt_eixo_oe { get; set; }
        public string? cmpl_add_od { get; set; }
        public string? base_od { get; set; }
        public string? diametro_od { get; set; }
        public string? cmpl_add_oe { get; set; }
        public string? base_oe { get; set; }
        public string? diametro_oe { get; set; }
        public string? ponte { get; set; }
        public string? altura { get; set; }
        public string? aro { get; set; }
        public string? diag_maior { get; set; }
        public string? dist_haste { get; set; }
        public string? dist_front { get; set; }
        public string? tipo_armacao { get; set; }
        public string? curvatura { get; set; }
        public string? id_produtos_opticos_tipo_aro { get; set; }
        public string? id_produtos_opticos_formato_aro { get; set; }
        public string? lng_dpdpn_od { get; set; }
        public string? prt_dpdpn_od { get; set; }
        public string? lng_dpdpn_oe { get; set; }
        public string? prt_dpdpn_oe { get; set; }
        public string? lng_altura_od { get; set; }
        public string? prt_altura_od { get; set; }
        public string? lng_altura_oe { get; set; }
        public string? prt_altura_oe { get; set; }
        public string? calibre { get; set; }
        public string? dp_montagem { get; set; }
        public string? observacao { get; set; }
        public string? paciente { get; set; }
        public string? endereco_paciente { get; set; }
        public string? medico_especialista { get; set; }
        public string? endereco_medico_especialista { get; set; }
        public string? refracionista_optico { get; set; }
        public string? data_receita { get; set; }
        public string? timestamp { get; set; }
        public string? id_ordservprod { get; set; }
        public string? id_vendas_pos_produtos_tmp { get; set; }
        public string? id_vendas_pos { get; set; }
        public string? cancelado { get; set; }
        public string? previsao_entrega { get; set; }
        public string? numero_ficha { get; set; }
        public string? id_vendas_pos_produtos_campos_adicionais_tmp { get; set; }
        public string? id_link_pagamento_linx_pay_hub { get; set; }
        public string? codigo_gerencial { get; set; }
        public string? empresa { get; set; }
        public string? origem { get; set; }
        public string? acoes_promocionais_desconto { get; set; }
        public string? desconto { get; set; }
        public string? acrescimo { get; set; }
        public string? frete { get; set; }
        public string? descontos_impostos { get; set; }
        public string? acrescimos_impostos { get; set; }
        public string? preco_unitario { get; set; }
        public string? quantidade { get; set; }
        public string? desconto_item { get; set; }
        public string? acrescimo_item_valor { get; set; }
        public string? desconto_item_valor { get; set; }
    }
}
