// <auto-generated />
using System;
using Infrastructure.Dootax.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Dootax.Data.Migrations.SQLServer
{
    [DbContext(typeof(DootaxTreatedDbContext))]
    [Migration("20250604071434_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Dootax.Entities.Parameters", b =>
                {
                    b.Property<Guid>("token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("token")
                        .HasAnnotation("Custom:ColumnTypeMapper", "UUID");

                    b.Property<string>("environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuario");

                    b.HasKey("token");

                    b.ToTable("Parametros_Dootax", "general");

                    b.HasData(
                        new
                        {
                            token = new Guid("87e2c224-fb6a-48c2-82da-8c57584b3169"),
                            environment = "prod",
                            user = "newbloomers"
                        },
                        new
                        {
                            token = new Guid("78391c28-0d30-4d8d-bbcd-735006165ecf"),
                            environment = "homolog",
                            user = "newbloomers"
                        });
                });

            modelBuilder.Entity("Domain.Dootax.Entities.SuccessfulLog", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("chave_nfe")
                        .IsRequired()
                        .HasColumnType("varchar(44)")
                        .HasColumnName("chave_nfe");

                    b.Property<string>("cnpj_emp")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cnpj_emp");

                    b.Property<int>("documento")
                        .HasColumnType("int")
                        .HasColumnName("documento");

                    b.Property<DateTime>("dt_insert")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_insert")
                        .HasAnnotation("Custom:ColumnTypeMapper", "DateTime");

                    b.Property<string>("serie")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("serie");

                    b.HasKey("id");

                    b.ToTable("Dootax_Successful_Log", "general");
                });
#pragma warning restore 612, 618
        }
    }
}
